[package]
name = "xml2yml_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.37.5"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_yaml = "0.9.34"
serde_yml = "0.0.12"
